name: Test and publish

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test

    strategy:
      matrix:
        device:
          - Desktop Chrome
          - Desktop Firefox
          - Desktop Safari
          - Pixel 7
          - iPhone 15

    permissions: {}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5

      - name: Install uv
        run: pip install -U pip uv

      - name: Install playwright
        run: uv run playwright install --with-deps

      - name: Run tests
        run: uv run pytest --device "${{ matrix.device }}"
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          BASIC_AUTH_USERNAME: ${{ secrets.BASIC_AUTH_USERNAME }}
          BASIC_AUTH_PASSWORD: ${{ secrets.BASIC_AUTH_PASSWORD }}
          ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          NURSE_USERNAME: ${{ secrets.NURSE_USERNAME }}
          NURSE_PASSWORD: ${{ secrets.NURSE_PASSWORD }}
          SUPERUSER_USERNAME: ${{ secrets.SUPERUSER_USERNAME }}
          SUPERUSER_PASSWORD: ${{ secrets.SUPERUSER_PASSWORD }}

      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.device }}
          path: allure-results

  publish:
    name: Publish

    needs: test

    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
        with:
          path: allure-results
          merge-multiple: true

      - uses: actions/setup-node@v4
        with:
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Generate Allura report
        run: npx allure generate allure-results

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report
